name: Publish Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: nginx

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [stable, mainline]
        platform: [alpine]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/nginx-brotli
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=${{ matrix.version }}-${{ matrix.platform }}
            type=raw,value=alpine,enable=${{ matrix.version == 'mainline' && matrix.platform == 'alpine' }}
            type=raw,value=latest,enable=${{ matrix.version == 'mainline' && matrix.platform == 'debian' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "{context}/Dockerfile.${{ matrix.version }}.${{ matrix.platform }}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
